[citation]
title = "Mauna Loa CO2 monthly mean data"
description = "Data from March 1958 through April 1974 have been obtained by C. David Keeling of the Scripps Institution of Oceanography (SIO) and were obtained from the Scripps website (scrippsco2.ucsd.edu). Monthly mean CO2 constructed from daily mean values Scripps data downloaded from http://scrippsco2.ucsd.edu/data/atmospheric_co2 Monthly values are corrected to center of month based on average seasonal cycle. Missing days can be asymmetric which would produce a high or low bias. Missing months have been interpolated, for NOAA data indicated by negative stdev and uncertainty. We have no information for SIO data about Ndays, stdv, unc so that they are also indicated by negative numbers"
authors = ["Dr. Pieter Tans", "Dr. Ralph Keeling"]
publication_date = "2022-06"
last_update = "2022-06"
publisher = "Dr. Pieter Tans, NOAA/GML (gml.noaa.gov/ccgg/trends/) and Dr. Ralph Keeling, Scripps Institution of Oceanography (scrippsco2.ucsd.edu/)."
id = ""
indra_id = "manualoaco2monthlymean"
indra_domain = "$event/geodata/historical/{dataset}/{column}"
version = ""
data_source = "https://gml.noaa.gov/webdata/ccgg/trends/co2/co2_mm_mlo.csv"
related_publications = ["https://gml.noaa.gov/ccgg/trends/data.html"]
tags = ["co2", "mauna_loa", "direct_measurement"]

[datasets]
manualoaco2monthlymean = [
    "decode('utf-8')",
    "remove_comments('#')",
    "pandas_csv_separator_nan(',', [-1, -9.99, -0.99])",
    "df['time_jd_start']=fracyear2julia(df['decimal date'])",
    "df['mean/co'] = df['average']",
    "df['deseasonalized/co2'] = df['deseasonalized']",
    "indra_import(time='time_jd_start', column='mean/co')",
    "indra_import(time='time_jd_start', column='deseasonalized/co2')",
]
