# Provisional main config

# Indrajala main application and async scheduler
[indrajala]
application="default"
systemd=false
modules=["in_async_mqtt","in_postgresql","in_signal_server","in_async_websockets", "in_csv_tree"]

# Signal server makes sure that only one instance of indrajala
# is running per host (using a default socket). It cana shutdown
# other instances (see -k startup option)
[in_signal_server]
active=true
signal_port=17417

# Postgresql storage
[in_postgresql]
active=true
connection="host='database-hostname' dbname='testdb' user='some-user'"

# Alternative storage backend based on files
[in_indrajala]
active=false
rootpath=""

[in_csv_tree]
active=true
rootpath="<some-path>/indrajala/python_indrajala/examples/csv_tree"

# MQTT interface based on PAHO MQTT
[in_async_mqtt]
active=true
startup_delay_sec=20
broker="mqtt-server-hostname"
topics=["#"]

# Websockets
[in_async_websockets]
active=false
port=23577
bind_address="0.0.0.0"
ssl=true
ssl_certfile="certs/certfile.pem"
ssl_keyfile="certs/keyfile.pem"

