[package]
name = "indrajala"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "*"
paho-mqtt = "*"
toml = "*"
async-channel = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
chrono = "*"
chrono-tz = "*"
tide = "*"
tide-rustls = "*"
