[indrajala]
logdir = "log"
max_loglevel_logfile = "debug"
modules = ["pingpong"]

[[pingpong]]
active = true
name = "pingpong.1"
loglevel = "debug"

[[pingpong]]
active = true
name = "pingpong.2"
loglevel = "debug"

[[pingpong]]
active = true
name = "pingpong.3"
loglevel = "debug"
