[indrajala]
logdir = "log"
max_loglevel_logfile = "debug"
loglevel = "info"
modules = ["pingpong", "indra_mqtt", "indra_db", "async_http", "indra_dispatch", "indra_ai"]
data_directory = "~/.config/indrajala"
zeromq_port = 8091

[[pingpong]]
active = false
zeromq_port = 8092
name = "pingpong.1"
loglevel = "debug"
subscriptions = ["pingpong/#"]
ping_frequency_hz = 1

[[pingpong]]
active = false
name = "pingpong.2"
loglevel = "debug"
subscriptions = ["pingpong/#"]
ping_frequency_hz = 1

[[pingpong]]
active = false
name = "pingpong.3"
loglevel = "debug"
subscriptions = ["pingpong/#"]
ping_frequency_hz = 1

[[indra_mqtt]]
active = false
name = "indra_mqtt.1"
loglevel = "debug"
subscriptions = ["mqtt/#"]
mqtt_server = "my-mqtt-server"
mqtt_port = 1883
mqtt_keepalive = 60
raw_mqtt_subscriptions = ["omu/#"]
inbound_parsers = [["omu/#", "muwerk"], ["hastates/#", "ha"]]
outbound_parsers = []

[[indra_db]]
active = true
name = "indra_db.1"
loglevel = "debug"
epsilon = 0.000001
subscriptions = []
database = "{{data_directory}}/db/indrajala.db"
commit_delay_sec = 0.0

[[async_http]]
active = true
name = "async_http.1"
loglevel = "debug"
subscriptions = []
port = 8080
bind_addresses = ["localhost"]
tls = true
private_key = "{{data_directory}}/certs/my-key.pem"
public_key = "{{data_directory}}/certs/my-cert.pem"
web_root = "{{data_directory}}/web"

[[indra_dispatch]]
active = true
name = "indra_dispatch.1"
loglevel = "debug"
subscriptions = []
annotate = ["sentiment"]

[[indra_ai]]
active = true
name = "indra_ai.1"
loglevel = "debug"
subscriptions = []
application = "sentiment"
engine = "huggingface/pipeline/sentiment-analysis"
model = "distilbert-base-uncased-finetuned-sst-2-english"
revision = "af0f99b"

[[indra_ai]]
active = true
name = "indra_ai.2"
loglevel = "debug"
subscriptions = []
application = "translation"
engine = "huggingface/accelerate/sentencepiece"
# model = "Helsinki-NLP/opus-mt-en-de"
model = "jbochi/madlad400-3b-mt"

[[zero_test]]
active = true
name = "zero_test.1"
zeromq_port = 8092
loglevel = "debug"
subscriptions = ["zero_test/#"]
