[indrajala]
logdir = "log"
max_loglevel_logfile = "debug"
modules = ["pingpong", "indra_mqtt", "indra_db", "async_http"]
data_directory = "~/.config/indrajala"

[[pingpong]]
active = false
name = "pingpong.1"
loglevel = "debug"
subscriptions = ["pingpong/#"]

[[pingpong]]
active = false
name = "pingpong.2"
loglevel = "debug"
subscriptions = ["pingpong/#"]

[[pingpong]]
active = false
name = "pingpong.3"
loglevel = "debug"
subscriptions = ["pingpong/#"]

[[indra_mqtt]]
active = false
name = "indra_mqtt.1"
loglevel = "debug"
subscriptions = ["mqtt/#"]
mqtt_server = "my-mqtt-server"
mqtt_port = 1883
mqtt_keepalive = 60
mqtt_subscriptions = ["something/#"]

[[indra_db]]
active = true
name = "indra_db.1"
loglevel = "debug"
subscriptions = ["mqtt/#"]
database = "{{data_directory}}/db/indrajala.db"


[[async_http]]
active = true
name = "async_http.1"
loglevel = "debug"
subscriptions = []
port = 8080
bind_addresses = ["localhost"]
tls = true
private_key = "{{data_directory}}/certs/my-key.pem"
public_key = "{{data_directory}}/certs/my-cert.pem"
web_root = "{{data_directory}}/web"
