[citation]
title="Geologic time scale"
description="The geologic time scale, or geological time scale, (GTS) is a representation of time based on the rock record of Earth. It is a system of chronological dating that uses chronostratigraphy (the process of relating strata to time) and geochronology (scientific branch of geology that aims to determine the age of rocks)."
authors=["Wikipedia"]
publication_date="2022"
last_update="2022"
publisher="Wikipedia"
id=""
version=""
data_source="https://en.wikipedia.org/wiki/Geologic_time_scale"
related_publications=["https://en.wikipedia.org/wiki/Geologic_time_scale"]
tags=['time_interval_names']

[datasets]
geologictimescale=[["extract_html_table", 4]]
