[citation]
title="Zeitreihen fuer Gebietsmittel fuer Bundeslaender und Kombinationen von Bundeslaender, erstellt am: 20220702"
description=""
authors=["DWD OpenData"]
publication_date="2022-07-02"
publisher="DWD OpenData"
id=""
version=""
data_source="https://opendata.dwd.de/climate_environment/CDC/regional_averages_DE/monthly/air_temperature_mean/regional_averages_tm_08.txt"
related_publications=["https://opendata.dwd.de/climate_environment/CDC/"]

[datasets]
germany_august_meantemp="decode_utf8,extract_lines(2:),csv_separator(';')"

