[citation]
title="GISP2 Ice Core Temperature and Accumulation Data"
short_title="gisp2icecore"
description="Greenland icecore temperature 49KYrBP - present. Temperature interpretation based on stable isotope analysis, and 
ice accumulation data, from the GISP2 ice core, central Greenland.  
Data are smoothed from original measurements published by 
Cuffey and Clow (1997), as presented in Figure 1 of Alley (2000)."
authors=["Alley, R.B."]
publication_date="2000"
last_update="2004-03"
publisher="IGBP PAGES/World Data Center for Paleoclimatology"
id="Quaternary Science Reviews 19:213-226."
version=""
data_source="ftp://ftp.ncdc.noaa.gov/pub/data/paleo/icecore/greenland/summit/gisp2/isotopes/gisp2_temp_accum_alley2000.txt"
related_publications=["https://www.pnas.org/doi/10.1073/pnas.97.4.1331"]

[transform]
downloader_transforms="decode_latin1"
csv_skiprows=74
csv_separator=" "
