name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always



jobs:
  build:
    name: Build
    
    runs-on: ubuntu-latest

# install pango

    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Install dependencies
      run: sudo apt-get install -y libpango1.0-dev libgraphene-1.0-0 libgraphene-1.0-dev libgtk-4-1 libgtk-4-bin libgtk-4-common libgtk-4-dev
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
